### PR TITLE
Revert 9 revert 8 master

### PR DESCRIPTION
**Pull request by shkodm**
The same as #8, but now working properly.  Previous PR contained silly typo with the path, that was accidently merged to a master due to github problems and then reverted.

### CODE REVIEW

**Comment by MakisH** [comment]
Feel free to merge when you feel it's ready!

**Comment by shkodm** [comment]
@MakisH , it is ready. Please merge, I don't have write access rights to this repository :)

**Comment by MakisH** [comment]
Merged, thanks! You now also have access. :)

Does it work for you? For me the Twitter feed is frozen (I am through a public wifi, maybe this has something to do).
screenshot from 2018-10-25 14-36-48

**Comment by shkodm** [comment]
Yep, it works 
image
Twitter loads slightly slower then the rest, but I guess it is fine ( since probably nobody will scroll down so fast to the bottom of the page right after going to the website )

**Comment by MakisH** [comment]
Looks like Chromium works immediately, but Firefox (62/Linux) does not load it even after a minute. I will also check later again. @uekerman does it work for you?

**Comment by uekerman** [comment]
first: nice work! thanks!
does work for me. also on firefox (also 62/Linux). 
what we could improve is the layout on phones. we should arrange both feeds vertically below a certain screen width.

**Comment by MakisH** [comment]
I found the scenario that breaks: in Firefox, I have the "tracking protection" enabled. This is also the default now in Firefox, I think, so we should have a look. I can also open an issue if I find out which part breaks.

**Pull request merged**
