### PR TITLE
Fix Sticky Header and add Github Icon

### LINKED ISSUE #14: Github Logo in Header
Put a github logo-link into the right side of the top bar and the responsive bar.

It is the most important link heading away from the website and should be as visible as possible.

### PR DESCRIPTION
**Pull request by fsimonis**
Reverting the sticky header from js to css makes the header more robust and removes the sticky delay on certain clients.

Fix #14

### CODE REVIEW

**Review by shkodm — CHANGES_REQUESTED** [review]
I just checked. First thing I've noticed, is that mobile menu also appears now for a brief moment and then dissapears ( checked on Chromium and Firefox ). Screenshot of this moment is below. 
image. I believe something like this was happening also in the beginning of Foundation port. Should probably be fixed. 

Regarding GitHub icon, I am not sure if the top right corner is the best location for it. Looks too far from main content and easy to miss it. However, I don't have a clear idea what would be a better place.

**Comment by fsimonis** [comment]
The flashing is a [problem with foundation](https://github.com/zurb/foundation-sites/issues/7252) and I will try to finally fix it in this PR.

**Comment by fsimonis** [comment]
@shkodm I finally fixed the FOUC and took the opportunity to refactor some of the breakpoint mechanics.

**Review by MakisH — APPROVED** [review]
Works nicely for me on the current state! I think that the placement of the GitHub button we can decide later. In any case, this is quite a standard location (and especially in the mobile version it looks very cool!)

**Review by shkodm — APPROVED** [review]

**Pull request merged**
