### PR TITLE
WIP: Add Timeline

### PR DESCRIPTION
**Pull request by fsimonis**
This PR contains a rough prototype of a preCICE Timeline.

# Preview
Large Screen | Small Screen
| --- | --- |
image|image

### CODE REVIEW

**Review by uekerman — APPROVED** [review]

**Review by MakisH — COMMENTED** [review]
Very beautiful and very educative! :D

Something to not forget: probably the "Timeline" menu item needs to move further to the left. The "About" is usually the last one. I think if we had `Publications --> Timeline --> About`, it would be nicer.

And a feature request: could we also have a link for each item (with the title as text)? We could link to each release, to conferences, to the repositories, etc. I see this page as another way to discover various aspects of the project.

**Comment by fsimonis** [comment]
@MakisH Additional Links should not be a problem

**Comment by fsimonis** [comment]
@MakisH All fixed.

What do we think about the design? I do not consider myself artistically minded when it comes to web design.

**Comment by MakisH** [comment]
The (visual) design looks good to me. I would only start thinking of it only when we see the website as a whole.

**Pull request merged**
